
package student.faculty.app;

import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class loginPortal extends javax.swing.JFrame {

    
    public loginPortal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        closePage = new javax.swing.JLabel();
        minimizeLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loginUsername = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        checkPass = new javax.swing.JCheckBox();
        loginStudent = new javax.swing.JButton();
        loginFaculty = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        studentSignup = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        facultySignup = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 427));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 190, 113));
        jPanel1.setMinimumSize(new java.awt.Dimension(526, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(526, 30));

        closePage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        closePage.setForeground(new java.awt.Color(255, 255, 255));
        closePage.setText("X");
        closePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closePageMouseClicked(evt);
            }
        });

        minimizeLogo.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        minimizeLogo.setForeground(new java.awt.Color(255, 255, 255));
        minimizeLogo.setText("-");
        minimizeLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLogoMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closePage)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closePage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minimizeLogo)))
                .addContainerGap(2, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setMinimumSize(new java.awt.Dimension(526, 320));
        jPanel3.setPreferredSize(new java.awt.Dimension(526, 320));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Username: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Password: ");

        loginUsername.setBackground(new java.awt.Color(0, 102, 102));
        loginUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginUsername.setForeground(new java.awt.Color(255, 255, 204));

        loginPasswordField.setBackground(new java.awt.Color(0, 102, 102));
        loginPasswordField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginPasswordField.setForeground(new java.awt.Color(255, 255, 204));

        checkPass.setBackground(new java.awt.Color(255, 255, 255));
        checkPass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkPass.setForeground(new java.awt.Color(204, 255, 255));
        checkPass.setText("Show");
        checkPass.setContentAreaFilled(false);
        checkPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPassActionPerformed(evt);
            }
        });

        loginStudent.setBackground(new java.awt.Color(102, 0, 0));
        loginStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginStudent.setForeground(new java.awt.Color(204, 255, 255));
        loginStudent.setText("Student Login");
        loginStudent.setBorderPainted(false);
        loginStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginStudentActionPerformed(evt);
            }
        });

        loginFaculty.setBackground(new java.awt.Color(102, 51, 0));
        loginFaculty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginFaculty.setForeground(new java.awt.Color(204, 255, 204));
        loginFaculty.setText("Faculty Login");
        loginFaculty.setBorderPainted(false);
        loginFaculty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFacultyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("New Student? Click here to create an account...");

        studentSignup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        studentSignup.setForeground(new java.awt.Color(255, 255, 102));
        studentSignup.setText("Sign Up");
        studentSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentSignupMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("New Teacher? Click here...");

        facultySignup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        facultySignup.setForeground(new java.awt.Color(255, 255, 102));
        facultySignup.setText("Sign up");
        facultySignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facultySignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facultySignupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addComponent(loginFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(loginStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(checkPass))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loginUsername)
                                .addComponent(loginPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facultySignup)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(studentSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginPasswordField)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkPass)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentSignup))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(facultySignup))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLogoMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLogoMouseClicked

    private void closePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePageMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closePageMouseClicked

    private void checkPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPassActionPerformed
        if(checkPass.isSelected()) {
            loginPasswordField.setEchoChar((char)0);
        } else {
            loginPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_checkPassActionPerformed

    private void studentSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentSignupMouseClicked
        signUpForm supStud = new signUpForm();
        supStud.setVisible(true);
        supStud.pack();
        supStud.setLocationRelativeTo(null);
        supStud.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_studentSignupMouseClicked

    private void facultySignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultySignupMouseClicked

        teacherSignUpAccess teachAcc = new teacherSignUpAccess();
        teachAcc.setVisible(true);
        teachAcc.pack();
        teachAcc.setLocationRelativeTo(null);
        teachAcc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
//        signUpFaculty supFac = new signUpFaculty();
//        supFac.setVisible(true);
//        supFac.pack();
//        supFac.setLocationRelativeTo(null);
//        supFac.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        
    }//GEN-LAST:event_facultySignupMouseClicked

    private void loginStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginStudentActionPerformed
        
        
        Connection con = myConnection.getConnection();
        PreparedStatement ps1, ps2;
        ResultSet rs1, rs2;
        
        try {
            ps1 = con.prepareStatement("SELECT `Id`, `studFname`, `collRollNo`, `studCourse`, `studBranch`, `studSem`, `studUsername`, `studPass`, `studPic` FROM `studsignup` WHERE `studUsername` = ? AND `studPass` = ?");
            ps1.setString(1, loginUsername.getText());
            ps1.setString(2, String.valueOf(loginPasswordField.getPassword()));
            
            
            rs1 = ps1.executeQuery();
            
            if(rs1.next()) {
                
//                teacherViewer.studCollId = rs.getInt("Id");
                studentPage stdPage = new studentPage();
                stdPage.setVisible(true);
                stdPage.pack();
                stdPage.setLocationRelativeTo(null);
                stdPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                stdPage.studProfilePic.setIcon(new myFunc().resizePic(null, rs1.getBytes(9), stdPage.studProfilePic.getWidth(), stdPage.studProfilePic.getHeight()));
                stdPage.studProfileName.setText(rs1.getString(2));
                stdPage.studProfileCollId.setText(rs1.getString(1));
                stdPage.studProfileRollNo.setText(rs1.getString(3));
                stdPage.studProfileCourse.setText(rs1.getString(4));
                stdPage.studProfileBranch.setText(rs1.getString(5));
                stdPage.studPageSem.setText(rs1.getString(6));
                
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Login Error");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(loginPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_loginStudentActionPerformed

    private void loginFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFacultyActionPerformed
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = con.prepareStatement("SELECT * FROM `facsignup` WHERE `tUsername` = ? AND `tPass` = ?");
            ps.setString(1, loginUsername.getText());
            ps.setString(2, String.valueOf(loginPasswordField.getPassword()));
            
            rs = ps.executeQuery();
            
            if(rs.next()) {
                
                
                
                teacherViewer tchPg = new teacherViewer();
                tchPg.setVisible(true);
                tchPg.pack();
                tchPg.setLocationRelativeTo(null);
                tchPg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                tchPg.teacherPortalPic.setIcon(new myFunc().resizePic(null, rs.getBytes(9), tchPg.teacherPortalPic.getWidth(), tchPg.teacherPortalPic.getHeight()));
                tchPg.teacherId.setText(rs.getString(1));
                tchPg.teacherGen.setText(rs.getString(3));
                tchPg.teachName.setText(rs.getString(2));
                tchPg.teachDepartment.setText(rs.getString(6));
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Login Error");
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(loginPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_loginFacultyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkPass;
    private javax.swing.JLabel closePage;
    private javax.swing.JLabel facultySignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginFaculty;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JButton loginStudent;
    private javax.swing.JTextField loginUsername;
    private javax.swing.JLabel minimizeLogo;
    private javax.swing.JLabel studentSignup;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("studFacIcon1.jpg")));
    }
}
