/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.faculty.app;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.GregorianCalendar;
/**
 *
 * @author Gulab Rai
 */
public class signUpFaculty extends javax.swing.JFrame {

    /**
     * Creates new form signUpFaculty
     */
    
    String imagePth = null;
    public signUpFaculty() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        signUpFacClose = new javax.swing.JLabel();
        signUpFacMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        teacherRegister = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        loginPage2 = new javax.swing.JLabel();
        teacherId = new javax.swing.JTextField();
        teacherName = new javax.swing.JTextField();
        teacherQualification = new javax.swing.JTextField();
        teacherAge = new javax.swing.JTextField();
        teacherGender = new javax.swing.JComboBox<>();
        teacherDepartment = new javax.swing.JTextField();
        teacherUsername = new javax.swing.JTextField();
        teachPasswordField1 = new javax.swing.JPasswordField();
        teachPasswordField2 = new javax.swing.JPasswordField();
        taechPic = new javax.swing.JLabel();
        teachPicIcon = new javax.swing.JLabel();
        teachPicBrowse = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(46, 190, 113));

        signUpFacClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signUpFacClose.setForeground(new java.awt.Color(255, 255, 255));
        signUpFacClose.setText("X");
        signUpFacClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpFacClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpFacCloseMouseClicked(evt);
            }
        });

        signUpFacMin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        signUpFacMin.setForeground(new java.awt.Color(255, 255, 255));
        signUpFacMin.setText("-");
        signUpFacMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpFacMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpFacMinMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Registration - Teacher");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(555, 555, 555)
                .addComponent(signUpFacMin)
                .addGap(18, 18, 18)
                .addComponent(signUpFacClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(signUpFacMin)
                    .addComponent(signUpFacClose))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(862, 465));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Teacher ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Teacher Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Department:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("D.O.B. :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Qualification:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Username:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Password:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Re-Type Password:");

        teacherRegister.setBackground(new java.awt.Color(153, 0, 0));
        teacherRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        teacherRegister.setForeground(new java.awt.Color(255, 204, 204));
        teacherRegister.setText("Register");
        teacherRegister.setBorderPainted(false);
        teacherRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRegisterActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Already registered? Click here...");

        loginPage2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginPage2.setForeground(new java.awt.Color(102, 0, 102));
        loginPage2.setText("Login");
        loginPage2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginPage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginPage2MouseClicked(evt);
            }
        });

        teacherId.setBackground(new java.awt.Color(204, 153, 255));
        teacherId.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        teacherId.setForeground(new java.awt.Color(0, 0, 51));

        teacherName.setBackground(new java.awt.Color(204, 153, 255));
        teacherName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        teacherName.setForeground(new java.awt.Color(0, 0, 51));
        teacherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherNameActionPerformed(evt);
            }
        });

        teacherQualification.setBackground(new java.awt.Color(204, 153, 255));
        teacherQualification.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        teacherQualification.setForeground(new java.awt.Color(0, 0, 51));

        teacherAge.setBackground(new java.awt.Color(204, 153, 255));
        teacherAge.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        teacherAge.setForeground(new java.awt.Color(0, 0, 51));

        teacherGender.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        teacherGender.setForeground(new java.awt.Color(153, 0, 0));
        teacherGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ms", "Mr", "Mrs" }));

        teacherDepartment.setBackground(new java.awt.Color(204, 153, 255));
        teacherDepartment.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        teacherDepartment.setForeground(new java.awt.Color(0, 0, 51));

        teacherUsername.setBackground(new java.awt.Color(204, 153, 255));
        teacherUsername.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        teacherUsername.setForeground(new java.awt.Color(0, 0, 51));
        teacherUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherUsernameActionPerformed(evt);
            }
        });

        teachPasswordField1.setBackground(new java.awt.Color(204, 153, 255));
        teachPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        teachPasswordField1.setForeground(new java.awt.Color(0, 0, 51));

        teachPasswordField2.setBackground(new java.awt.Color(204, 153, 255));
        teachPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        teachPasswordField2.setForeground(new java.awt.Color(0, 0, 51));

        taechPic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        taechPic.setForeground(new java.awt.Color(204, 255, 255));
        taechPic.setText("Picture:");

        teachPicIcon.setBackground(new java.awt.Color(204, 153, 255));
        teachPicIcon.setOpaque(true);

        teachPicBrowse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teachPicBrowse.setText("Browse");
        teachPicBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teachPicBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachPicBrowseActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("(Size should be less than 1MB)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Format (YYYY-MM-DD)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(teacherId, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(teacherAge, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(jLabel13))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teachPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teachPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(taechPic)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teachPicIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(teachPicBrowse))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(teacherRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(loginPage2))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(teacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teacherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teacherAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(3, 3, 3)
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacherQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacherDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacherUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teachPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teachPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(taechPic, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(teachPicIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(teachPicBrowse)))
                .addGap(43, 43, 43)
                .addComponent(teacherRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(loginPage2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpFacCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpFacCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_signUpFacCloseMouseClicked

    private void signUpFacMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpFacMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_signUpFacMinMouseClicked

    private void loginPage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPage2MouseClicked
        loginPortal login2 = new loginPortal();
        login2.setVisible(true);
        login2.pack();
        login2.setLocationRelativeTo(null);
        login2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_loginPage2MouseClicked

    
    public boolean verifyData2() {
        
        if(teacherId.getText().equals("") || teacherName.getText().equals("") 
                || teacherAge.getText().equals("") || teacherQualification.getText().equals("")
                || teacherDepartment.getText().equals("") || teacherUsername.getText().equals("")
                || teacherGender.getActionCommand().equals("")
                || String.valueOf(teachPasswordField1.getPassword()).equals("")) {
//            JOptionPane.showMessageDialog(null, "Pic size should be less than 1mb \r\n ---------------- OR ---------------- \r\n Date Format - YYYY-MM-DD" );
            JOptionPane.showMessageDialog(null, "One or More Field are empty");
            return false;
        } else if(!String.valueOf(teachPasswordField1.getPassword()).equals(String.valueOf(teachPasswordField2.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Incorrect Password!!");
            return false;
        } else if(imagePth == null){
            JOptionPane.showMessageDialog(null, "No Image Selected");
            return false;
        } else {
            return true;
        }
      
    }
    
    
    private void teacherRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherRegisterActionPerformed
        
        if(verifyData2()) {
            Connection con = myConnection.getConnection();
            PreparedStatement ps;
        
            try {
                ps = con.prepareStatement("INSERT INTO `facsignup`(`facId`, `tName`, `tGender`, `tAge`, `tQual`, `tDepartmnt`, `tUsername`, `tPass`, `teachPicture`) VALUES (?,?,?,?,?,?,?,?,?)");
                ps.setString(1, teacherId.getText());
                ps.setString(2, teacherName.getText());
                ps.setString(3, teacherGender.getSelectedItem().toString());
     //                Date teachAge = 
                
                ps.setString(4, teacherAge.getText());
                ps.setString(5, teacherQualification.getText());
                ps.setString(6, teacherDepartment.getText());
                ps.setString(7, teacherUsername.getText());
                ps.setString(8, String.valueOf(teachPasswordField1.getPassword()));
                
                InputStream img = new FileInputStream(new File(imagePth));
                ps.setBlob(9, img);
                
                if(ps.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "Account Created!!");
                    teacherId.setText("");
                    teacherName.setText("");
                    teacherAge.setText("");
                    teacherQualification.setText("");
                    teacherDepartment.setText("");
                    teacherUsername.setText("");
                    teachPasswordField1.setText("");
                    teachPasswordField2.setText("");
                    teachPicIcon.setIcon(null);
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Something Wrong!!");
                }
            
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Pic size should be less than 1mb \r\n ---------------- OR ---------------- \r\n Date Format - YYYY-MM-DD" );
            }
        }
        
        
        
    }//GEN-LAST:event_teacherRegisterActionPerformed

    private void teachPicBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachPicBrowseActionPerformed
        myFunc mf = new myFunc();
        imagePth = mf.browseImage(teachPicIcon);
        System.out.println(imagePth);
    }//GEN-LAST:event_teachPicBrowseActionPerformed

    private void teacherUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherUsernameActionPerformed

    private void teacherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUpFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUpFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUpFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUpFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUpFaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel loginPage2;
    private javax.swing.JLabel signUpFacClose;
    private javax.swing.JLabel signUpFacMin;
    private javax.swing.JLabel taechPic;
    private javax.swing.JPasswordField teachPasswordField1;
    private javax.swing.JPasswordField teachPasswordField2;
    private javax.swing.JButton teachPicBrowse;
    private javax.swing.JLabel teachPicIcon;
    private javax.swing.JTextField teacherAge;
    private javax.swing.JTextField teacherDepartment;
    private javax.swing.JComboBox<String> teacherGender;
    private javax.swing.JTextField teacherId;
    private javax.swing.JTextField teacherName;
    private javax.swing.JTextField teacherQualification;
    private javax.swing.JButton teacherRegister;
    private javax.swing.JTextField teacherUsername;
    // End of variables declaration//GEN-END:variables
}
