/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.faculty.app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gulab Rai
 */
public class studentMarks extends javax.swing.JFrame {

    /**
     * Creates new form studentMarks
     */
    public studentMarks() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studMarksId = new javax.swing.JLabel();
        studMarksName = new javax.swing.JLabel();
        studMarksSem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        studSub1 = new javax.swing.JTextField();
        studSub1Marks = new javax.swing.JTextField();
        studSub2 = new javax.swing.JTextField();
        studSub2Marks = new javax.swing.JTextField();
        studSub3 = new javax.swing.JTextField();
        studSub3Marks = new javax.swing.JTextField();
        studSub4 = new javax.swing.JTextField();
        studSub4Marks = new javax.swing.JTextField();
        studSub5 = new javax.swing.JTextField();
        studSub5Marks = new javax.swing.JTextField();
        studSub6 = new javax.swing.JTextField();
        studSub6Marks = new javax.swing.JTextField();
        updateStudResult = new javax.swing.JButton();
        teacherID = new javax.swing.JLabel();
        deleteStudMarks = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Marks");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<<");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(185, 185, 185)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("College ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Semester:");

        studMarksId.setBackground(new java.awt.Color(204, 204, 204));
        studMarksId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studMarksId.setForeground(new java.awt.Color(0, 51, 102));
        studMarksId.setText("id");
        studMarksId.setOpaque(true);

        studMarksName.setBackground(new java.awt.Color(204, 204, 204));
        studMarksName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studMarksName.setForeground(new java.awt.Color(0, 51, 102));
        studMarksName.setText("  nm");
        studMarksName.setOpaque(true);

        studMarksSem.setBackground(new java.awt.Color(204, 204, 204));
        studMarksSem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studMarksSem.setForeground(new java.awt.Color(0, 51, 102));
        studMarksSem.setText("  sem");
        studMarksSem.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Subjects");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Marks");

        studSub1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub1.setForeground(new java.awt.Color(0, 51, 102));

        studSub1Marks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub1Marks.setForeground(new java.awt.Color(0, 51, 102));

        studSub2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub2.setForeground(new java.awt.Color(0, 51, 102));

        studSub2Marks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub2Marks.setForeground(new java.awt.Color(0, 51, 102));

        studSub3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub3.setForeground(new java.awt.Color(0, 51, 102));

        studSub3Marks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub3Marks.setForeground(new java.awt.Color(0, 51, 102));

        studSub4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub4.setForeground(new java.awt.Color(0, 51, 102));

        studSub4Marks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub4Marks.setForeground(new java.awt.Color(0, 51, 102));

        studSub5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub5.setForeground(new java.awt.Color(0, 51, 102));

        studSub5Marks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub5Marks.setForeground(new java.awt.Color(0, 51, 102));

        studSub6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub6.setForeground(new java.awt.Color(0, 51, 102));

        studSub6Marks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSub6Marks.setForeground(new java.awt.Color(0, 51, 102));

        updateStudResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateStudResult.setForeground(new java.awt.Color(0, 0, 51));
        updateStudResult.setText("Update");
        updateStudResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateStudResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudResultActionPerformed(evt);
            }
        });

        teacherID.setForeground(new java.awt.Color(153, 255, 255));
        teacherID.setText("jLabel10");

        deleteStudMarks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteStudMarks.setForeground(new java.awt.Color(0, 0, 51));
        deleteStudMarks.setText("Delete");
        deleteStudMarks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteStudMarks.setMaximumSize(new java.awt.Dimension(97, 31));
        deleteStudMarks.setMinimumSize(new java.awt.Dimension(97, 31));
        deleteStudMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudMarksActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("(Click here to delete previous data)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(151, 151, 151))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studMarksName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studMarksSem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(studMarksId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(teacherID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studSub6, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(studSub5)
                            .addComponent(studSub4)
                            .addComponent(studSub3)
                            .addComponent(studSub2)
                            .addComponent(studSub1))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studSub1Marks)
                            .addComponent(studSub2Marks)
                            .addComponent(studSub3Marks)
                            .addComponent(studSub4Marks)
                            .addComponent(studSub5Marks)
                            .addComponent(studSub6Marks, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(deleteStudMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(updateStudResult, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(studMarksId)
                    .addComponent(teacherID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(studMarksName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(studMarksSem))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studSub1Marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studSub2Marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studSub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studSub3Marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studSub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studSub4Marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studSub5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studSub5Marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studSub6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studSub6Marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateStudResult, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStudMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = con.prepareStatement("SELECT * FROM `facsignup` WHERE `facId` = ?");
            ps.setString(1, teacherID.getText());
            
            
            rs = ps.executeQuery();
            
            if(rs.next()) {
                
                
                
                teacherViewer tchPg = new teacherViewer();
                tchPg.setVisible(true);
                tchPg.pack();
                tchPg.setLocationRelativeTo(null);
                tchPg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                tchPg.teacherPortalPic.setIcon(new myFunc().resizePic(null, rs.getBytes(9), tchPg.teacherPortalPic.getWidth(), tchPg.teacherPortalPic.getHeight()));
                tchPg.teacherId.setText(rs.getString(1));
                tchPg.teacherGen.setText(rs.getString(3));
                tchPg.teachName.setText(rs.getString(2));
                tchPg.teachDepartment.setText(rs.getString(6));
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Login Error");
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(loginPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        teacherViewer tch = new teacherViewer();
//        tch.setVisible(true);
//        tch.pack();
//        tch.setLocationRelativeTo(null);
//        tch.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        
//        
//        this.dispose();
        
    }//GEN-LAST:event_jLabel7MouseClicked

    
    public boolean verifyDataEnt() {
        
//        if(isUsernameExist(studMarksId.getText())) {
//            delete();
//            JOptionPane.showMessageDialog(null, "Not Done??");
//            return false;
//            
//        } else 
            if(studSub1.getText().equals("") || studSub1Marks.getText().equals("") || studSub2.getText().equals("") || studSub2Marks.getText().equals("") 
                || studSub3.getText().equals("") || studSub3Marks.getText().equals("") || studSub4.getText().equals("") || 
                studSub4Marks.getText().equals("") || studSub5.getText().equals("") || studSub5Marks.getText().equals("") ||
                studSub6.getText().equals("") || studSub6Marks.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "One or More Field are empty");
            return false;
        } else {
            return true;
        }
        
        
    }
    
    public boolean isUsernameExist(String un) {
        
        boolean uExist = false;
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = con.prepareStatement("SELECT * FROM `studsubjects_&_marks` WHERE `studCollId` = ?");
            ps.setString(1, studMarksId.getText());
            
            
            rs = ps.executeQuery();
            
            if(rs.next()) {
                uExist = true;
            } 
            
        } catch (SQLException ex) {
            Logger.getLogger(loginPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return uExist;
    }
    
    
    
//    public void delete() {
//        
//        Connection con = myConnection.getConnection();
//        PreparedStatement ps;
//        
//        try {
//            
//            ps = con.prepareStatement("INSERT INTO `studsubjects_&_marks`(`studCollId`) VALUES (?)");
//            ps.setString(1, studMarksId.getText());
//            
//            ps = con.prepareStatement("DELETE FROM `studsubjects_&_marks` WHERE `studCollId` = ?");
//            ps.setString(1, studMarksId.getText());
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(studentMarks.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        
//    }
    
    private void updateStudResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudResultActionPerformed
        
         
            
//            try {
//                PreparedStatement ps = myConnection.getConnection().prepareStatement("DELETE FROM `studsubjects_&_marks` WHERE `studCollId` = ?");
//                ps.setString(1, studMarksId.getText());
//            
//            } catch (SQLException ex) {
//                Logger.getLogger(studentMarks.class.getName()).log(Level.SEVERE, null, ex);
//            }
         
              
                          
                if(verifyDataEnt()) {

                    Connection con = myConnection.getConnection();
                    PreparedStatement ps;

                    try {
                        ps = con.prepareStatement("INSERT INTO `studsubjects_&_marks`(`studSub1`, `studSub1Marks`, `studSub2`, `studSub2Marks`,"
                            + " `studSub3`, `studSub3Marks`, `studSub4`, `studSub4Marks`, `studSub5`, `studSub5Marks`, `studSub6`, `studSub6Marks`, `studCollId`) "
                            + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)");
                        ps.setString(1, studSub1.getText());
                        ps.setString(2, studSub1Marks.getText());
                        ps.setString(3, studSub2.getText());
                        ps.setString(4, studSub2Marks.getText());
                        ps.setString(5, studSub3.getText());
                        ps.setString(6, studSub3Marks.getText());
                        ps.setString(7, studSub4.getText());
                        ps.setString(8, studSub4Marks.getText());
                        ps.setString(9, studSub5.getText());
                        ps.setString(10, studSub5Marks.getText());
                        ps.setString(11, studSub6.getText());
                        ps.setString(12, studSub6Marks.getText());
                        ps.setString(13, studMarksId.getText());


                        if(isUsernameExist(studMarksId.getText())) {
                            JOptionPane.showMessageDialog(null, "Already have");
                        } else {
                            if(ps.executeUpdate() != 0) {
                                JOptionPane.showMessageDialog(null, "Marks Added!!");
                                studSub1.setText("");
                                studSub1Marks.setText("");
                                studSub2.setText("");
                                studSub2Marks.setText("");
                                studSub3.setText("");
                                studSub3Marks.setText("");
                                studSub4.setText("");
                                studSub4Marks.setText("");
                                studSub5.setText("");
                                studSub5Marks.setText("");
                                studSub6.setText("");
                                studSub6Marks.setText("");
                            } else {
                                JOptionPane.showMessageDialog(null, "Something Wrong!!");
                            }
                        }
                        
                           
                        




                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }

                }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_updateStudResultActionPerformed

    private void deleteStudMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudMarksActionPerformed
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        
        try {
            
            ps = con.prepareStatement("DELETE FROM `studsubjects_&_marks` WHERE `studCollId` = ?");
            ps.setString(1, studMarksId.getText());
            
            if(ps.executeUpdate() != 0) {
                JOptionPane.showMessageDialog(null, "Deleted!!");
            } else {
                JOptionPane.showMessageDialog(null, "No Data found!!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(studentMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteStudMarksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteStudMarks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel studMarksId;
    public javax.swing.JLabel studMarksName;
    public javax.swing.JLabel studMarksSem;
    private javax.swing.JTextField studSub1;
    private javax.swing.JTextField studSub1Marks;
    private javax.swing.JTextField studSub2;
    private javax.swing.JTextField studSub2Marks;
    private javax.swing.JTextField studSub3;
    private javax.swing.JTextField studSub3Marks;
    private javax.swing.JTextField studSub4;
    private javax.swing.JTextField studSub4Marks;
    private javax.swing.JTextField studSub5;
    private javax.swing.JTextField studSub5Marks;
    private javax.swing.JTextField studSub6;
    private javax.swing.JTextField studSub6Marks;
    public javax.swing.JLabel teacherID;
    private javax.swing.JButton updateStudResult;
    // End of variables declaration//GEN-END:variables
}
