/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.faculty.app;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;



public class teacherViewer extends javax.swing.JFrame {

    /**
     * Creates new form teacherViewer
     */
    
    public static int studCollId;
    public teacherViewer() {
        initComponents();
        this.setLocationRelativeTo(null);
        populateJtable(); 
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.GREEN);
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.red);
        th.setFont(new Font("Tahoma", Font.PLAIN, 13));
//        System.out.println(studCollId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teacherPortalClose = new javax.swing.JLabel();
        teacherMin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        teacherGen = new javax.swing.JLabel();
        teacherId = new javax.swing.JLabel();
        teachName = new javax.swing.JLabel();
        teachDepartment = new javax.swing.JLabel();
        teacherPortalPic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 534));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(760, 32));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher Portal");

        teacherPortalClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        teacherPortalClose.setForeground(new java.awt.Color(255, 255, 255));
        teacherPortalClose.setText("X");
        teacherPortalClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherPortalClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherPortalCloseMouseClicked(evt);
            }
        });

        teacherMin.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        teacherMin.setForeground(new java.awt.Color(255, 255, 255));
        teacherMin.setText("-");
        teacherMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherMinMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("LOG OUT");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211)
                .addComponent(teacherMin)
                .addGap(18, 18, 18)
                .addComponent(teacherPortalClose)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(teacherPortalClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teacherMin, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        teacherGen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        teacherGen.setForeground(new java.awt.Color(255, 102, 102));
        teacherGen.setText("gen");

        teacherId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        teacherId.setForeground(new java.awt.Color(255, 102, 102));
        teacherId.setText("id");

        teachName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        teachName.setForeground(new java.awt.Color(255, 102, 102));
        teachName.setText("name");

        teachDepartment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        teachDepartment.setForeground(new java.awt.Color(255, 102, 102));
        teachDepartment.setText("depart");

        teacherPortalPic.setBackground(new java.awt.Color(204, 204, 204));
        teacherPortalPic.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Teacher ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Department:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "College Id", "Name", "Course", "Branch", "Semester", "Roll no."
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("NOTICE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(teacherPortalPic, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(teacherGen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teachName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(236, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(teachDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(54, 54, 54))))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacherId)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teachName)
                            .addComponent(teacherGen)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(teachDepartment)
                            .addComponent(jButton1)))
                    .addComponent(teacherPortalPic, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String imagePth = null;
    myFunc mf = new myFunc();
    
    public void populateJtable() {
        
//        studAssignments2Query sq = new studAssignments2Query();
//        ArrayList<studAssignments> stList = sq.studList();
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        Statement st;
        ResultSet rs;
        
//        String[] colNames = {"College Id", "Name", "Assignment", "Student Query"};
//        Object[][] rows = new Object[stList.size()][4];
        
         
        try {
//            ps = con.prepareStatement("SELECT `Id`, `studFname`, `collRollNo`, `studCourse`, `studBranch`, `studSem` FROM `studsignup` ");
            st = con.createStatement();
            String sql = "SELECT `Id`, `studFname`, `collRollNo`, `studCourse`, `studBranch`, `studSem`, `studPic` FROM `studsignup` ";
            rs = st.executeQuery(sql);
            
            while(rs.next()) {
                
                String id = String.valueOf(rs.getInt("Id"));
                String stdNme = String.valueOf(rs.getString("studFname"));
                String collRoln = String.valueOf(rs.getString("collRollNo"));
                String course = String.valueOf(rs.getString("studCourse"));
                String branch = String.valueOf(rs.getString("studBranch"));
                String sem = String.valueOf(rs.getInt("studSem"));
                
//                imagePth = mf.resizePic(null, rs.getBytes("studPic"), 50, 50);
//                ImageIcon pic = new ImageIcon(new ImageIcon(rs.getBytes("studPic")).getImage().getScaledInstance(48, 48, Image.SCALE_SMOOTH));
//                ImageIcon pic = new ImageIcon(mf.resizePic(null, rs.getBytes("studPic"), 48, 48));
//                String Pic = String.valueOf(new ImageIcon(rs.getBytes("studPic")).getImage());
                
                
                String tbData[] = {id, stdNme, course, branch, sem, collRoln};
               
                DefaultTableModel tblMod = (DefaultTableModel)jTable1.getModel();
                
                tblMod.addRow(tbData);
                
                
            }
            
            
            
        
//            for(int i = 0; i < stList.size(); i++) {
//            
//                rows[i][0] = stList.get(i).getStudId();
//                rows[i][1] = stList.get(i).getDocfile().toString();
//                rows[i][2] = stList.get(i).getStudQuery();
//                rows[i][3] = stList.get(i).getUid();
//            }
            
                
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(teacherViewer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
//        MyModel mmd = new MyModel(rows, colNames);
        
//        jTable1.setModel(mmd);
        jTable1.setRowHeight(50);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
        
    }
    
    
    private void teacherPortalCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherPortalCloseMouseClicked
       System.exit(0);
    }//GEN-LAST:event_teacherPortalCloseMouseClicked

    private void teacherMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_teacherMinMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int rowIndex = jTable1.getSelectedRow();
        
        
        studentMarks stdmks = new studentMarks();
        stdmks.setVisible(true);
        stdmks.pack();
        stdmks.setLocationRelativeTo(null);
        stdmks.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        stdmks.studMarksId.setText(jTable1.getValueAt(rowIndex, 0).toString());
        stdmks.studMarksName.setText(jTable1.getValueAt(rowIndex, 1).toString());
        stdmks.studMarksSem.setText(jTable1.getValueAt(rowIndex, 4).toString());
        stdmks.teacherID.setText(teacherId.getText());
        this.dispose();
//        upsd.studPic.setIcon(new myFunc().resizePic(null, rs.getBytes(9), upsd.studPic.getWidth(), upsd.studPic.getHeight()));        
//        setText(rs.getString(1));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        notice n = new notice();
        n.setVisible(true);
        n.pack();
        n.setLocationRelativeTo(null);
        n.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        loginPortal login = new loginPortal();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JLabel teachDepartment;
    public javax.swing.JLabel teachName;
    public javax.swing.JLabel teacherGen;
    public javax.swing.JLabel teacherId;
    private javax.swing.JLabel teacherMin;
    private javax.swing.JLabel teacherPortalClose;
    public javax.swing.JLabel teacherPortalPic;
    // End of variables declaration//GEN-END:variables
}
