/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.faculty.app;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Blob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gulab Rai
 */
public class updateStud extends javax.swing.JFrame {

    /**
     * Creates new form updateStud
     */
    String imgPth = null;
    public updateStud() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studName = new javax.swing.JTextField();
        studBranch = new javax.swing.JTextField();
        studSem = new javax.swing.JTextField();
        studCollId = new javax.swing.JTextField();
        studPic = new javax.swing.JLabel();
        studPicBrowse = new javax.swing.JButton();
        studInfoUpdate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        studRollno = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        usernameUpdate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        showPassUpdate = new javax.swing.JCheckBox();
        passwordUpdate = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UPDATE INFO");

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("<<BACK");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(315, 315, 315)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Course:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Branch:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Semester:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("College Id:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Picture:");

        studName.setBackground(new java.awt.Color(204, 255, 255));
        studName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studName.setForeground(new java.awt.Color(0, 51, 51));

        studBranch.setBackground(new java.awt.Color(204, 255, 255));
        studBranch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studBranch.setForeground(new java.awt.Color(0, 51, 51));

        studSem.setBackground(new java.awt.Color(204, 255, 255));
        studSem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studSem.setForeground(new java.awt.Color(0, 51, 51));

        studCollId.setBackground(new java.awt.Color(204, 255, 255));
        studCollId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studCollId.setForeground(new java.awt.Color(0, 51, 51));

        studPic.setBackground(new java.awt.Color(204, 255, 255));
        studPic.setOpaque(true);

        studPicBrowse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studPicBrowse.setText("Browse");
        studPicBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studPicBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studPicBrowseActionPerformed(evt);
            }
        });

        studInfoUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studInfoUpdate.setText("Update");
        studInfoUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studInfoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studInfoUpdateActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("Roll No.:");

        studRollno.setBackground(new java.awt.Color(204, 255, 255));
        studRollno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studRollno.setForeground(new java.awt.Color(0, 51, 51));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech.", "BCA", "BBA", "M.Tech.", "MCA", "MBA" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Username:");

        usernameUpdate.setEditable(false);
        usernameUpdate.setBackground(new java.awt.Color(204, 255, 255));
        usernameUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameUpdate.setForeground(new java.awt.Color(0, 51, 51));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Password:");

        showPassUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        showPassUpdate.setText("Show ");
        showPassUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassUpdateActionPerformed(evt);
            }
        });

        passwordUpdate.setBackground(new java.awt.Color(204, 255, 255));
        passwordUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordUpdate.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studName)
                                    .addComponent(studBranch)
                                    .addComponent(studSem)
                                    .addComponent(studCollId)
                                    .addComponent(studRollno)
                                    .addComponent(jComboBox1, 0, 188, Short.MAX_VALUE))
                                .addGap(88, 88, 88)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(usernameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(showPassUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(passwordUpdate))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(studPic, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addComponent(studPicBrowse))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(studInfoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studPicBrowse)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(studName)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studBranch)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studSem)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studCollId)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(studRollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPassUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(studInfoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = con.prepareStatement("SELECT `Id`, `studFname`, `collRollNo`, `studCourse`, `studBranch`, `studSem`, `studUsername`, `studPass`, `studPic` FROM `studsignup` WHERE `Id` = ? ");
            ps.setString(1, studCollId.getText());
            
            
            rs = ps.executeQuery();
            
            if(rs.next()) {
                

                studentPage stdPage = new studentPage();
                stdPage.setVisible(true);
                stdPage.pack();
                stdPage.setLocationRelativeTo(null);
                stdPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                stdPage.studProfilePic.setIcon(new myFunc().resizePic(null, rs.getBytes(9), stdPage.studProfilePic.getWidth(), stdPage.studProfilePic.getHeight()));
                stdPage.studProfileName.setText(rs.getString(2));
                stdPage.studProfileCollId.setText(rs.getString(1));
                stdPage.studProfileRollNo.setText(rs.getString(3));
                stdPage.studProfileCourse.setText(rs.getString(4));
                stdPage.studProfileBranch.setText(rs.getString(5));
                stdPage.studPageSem.setText(rs.getString(6));
                
                this.dispose();
                
            } 
        } catch (SQLException ex) {
            Logger.getLogger(loginPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
//        studentPage stdPage = new studentPage();
//        stdPage.setVisible(true);
//        stdPage.pack();
//        stdPage.setLocationRelativeTo(null);
//        stdPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.dispose();


    }//GEN-LAST:event_jLabel10MouseClicked

    private void studInfoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studInfoUpdateActionPerformed

        String updateQuery = "";
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        
        if(imgPth != null) {
            
            try {
                int studId = Integer.valueOf(studCollId.getText());
                String stdName = studName.getText();
                String studRln = studRollno.getText();
                String studCourse = jComboBox1.getSelectedItem().toString();
                String stdBrnch = studBranch.getText();
                String stdSem = studSem.getText();
                String stdUsername = usernameUpdate.getText();
                String stdPass = String.valueOf(passwordUpdate.getPassword());
                InputStream img = new FileInputStream(new File(imgPth));
            
//            byte img[] = null;
//            Path pth = Paths.get(imgPth);
//            img = Files.readAllBytes(pth);


                updateQuery = "UPDATE `studsignup` SET `Id`= '"+studId+"',`studFname`= '"+stdName+"',"
                                                 + "`collRollNo`= '"+studRln+"',`studCourse`= '"+studCourse+"',"
                                                 + "`studBranch`= '"+stdBrnch+"',`studSem`= '"+stdSem+"',`studUsername`= '"+stdUsername+"',"
                                                 + "`studPass`= '"+stdPass+"',`studPic`= ? WHERE `studUsername`= '"+stdUsername+"' ";



                ps = con.prepareStatement(updateQuery);
                ps.setBlob(1, img);
                ps.execute();

                JOptionPane.showMessageDialog(null, "Updated");
                
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Something Wrong");
            } 
            
        } else {
            
            try {
                int studId = Integer.valueOf(studCollId.getText());
                String stdName = studName.getText();
                String studRln = studRollno.getText();
                String studCourse = jComboBox1.getSelectedItem().toString();
                String stdBrnch = studBranch.getText();
                String stdSem = studSem.getText();
                String stdUsername = usernameUpdate.getText();
                String stdPass = String.valueOf(passwordUpdate.getPassword());
                
                
                updateQuery = "UPDATE `studsignup` SET `Id`= '"+studId+"',`studFname`= '"+stdName+"',"
                                                 + "`collRollNo`= '"+studRln+"',`studCourse`= '"+studCourse+"',"
                                                 + "`studBranch`= '"+stdBrnch+"',`studSem`= '"+stdSem+"',`studUsername`= '"+stdUsername+"',"
                                                 + "`studPass`= '"+stdPass+"' WHERE `studUsername`= '"+stdUsername+"' ";
                
                
                ps = con.prepareStatement(updateQuery);
                
                ps.execute();

                JOptionPane.showMessageDialog(null, "Updated");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            } 
            
        }
        
        
        
            
            
            
//         `Id`= ?    
            
            
            
            
            
            
            
            
            
//        if(imgPth != null) {
//            
//            byte[] img = null;
//            try {
//                Path pth = Paths.get(imgPth);
//                img = Files.readAllBytes(pth);
//                
//                updateStudInfo(true);
//            } catch (IOException ex) { 
//                Logger.getLogger(updateStud.class.getName()).log(Level.SEVERE, null, ex);
//            } 
//        } else {
//            
//            updateStudInfo(false);
//        }
//




//        updateQuery = "UPDATE `studsignup` SET `Id`= ?,`studFname`= ?,`collRollNo`= ?,`studCourse`= ?,`studBranch`= ?,`studSem`= ?,`studUsername`= ?,`studPass`= ?,`studPic`= ? WHERE `Id`= ?";



//                if(ps.executeUpdate() != 0) {
//                    JOptionPane.showMessageDialog(null, "Updated");
//                }else{
//                    JOptionPane.showMessageDialog(null, "Something Wrong");
//                }
        


            
         
        
        
        
        
    }//GEN-LAST:event_studInfoUpdateActionPerformed

//    public void updateStudInfo(boolean withImage) {
//        Connection con = myConnection.getConnection();
//        PreparedStatement ps;
//        String updateQuery = "";
//        
//        if(withImage == true) {
//            
//            updateQuery = "UPDATE `studsignup` SET `Id`= ?,`studFname`= ?,`collRollNo`= ?,`studCourse`= ?,`studBranch`= ?,`studSem`= ?,`studUsername`= ?,`studPass`= ?,`studPic`= ? WHERE `Id`= ?";
//            
//            try {
//                ps = con.prepareStatement(updateQuery);
//                ps.setString(1, studCollId.getText());
//                ps.setString(2, studName.getText());
//                ps.setString(3, studRollno.getText());
//                ps.setString(4, jComboBox1.getSelectedItem().toString());
//                ps.setString(5, studBranch.getText());
//                ps.setString(6, studSem.getText());
//                ps.setString(7, usernameUpdate.getText());
//                ps.setString(8, String.valueOf(passwordUpdate.getPassword()));
//                ps.setBytes(9, imgPth.getBytes());
////                InputStream img = new FileInputStream(new File(imgPth));
////                ps.setBlob(9, img);
//
//                if(ps.executeUpdate() != 0) {
//                    JOptionPane.showMessageDialog(null, "Updated");
//                }else{
//                    JOptionPane.showMessageDialog(null, "Something Wrong");
//                }
//            
//            
//            } catch (SQLException ex) {
//                Logger.getLogger(updateStud.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//            
//        } else {
//            
//            updateQuery = "UPDATE `studsignup` SET `Id`= ?,`studFname`= ?,`collRollNo`= ?,`studCourse`= ?,`studBranch`= ?,`studSem`= ?,`studUsername`= ?,`studPass`= ? WHERE `Id`= ?";
//            
//            try {
//                ps = con.prepareStatement(updateQuery);
//                ps.setString(1, studCollId.getText());
//                ps.setString(2, studName.getText());
//                ps.setString(3, studRollno.getText());
//                ps.setString(4, jComboBox1.getSelectedItem().toString());
//                ps.setString(5, studBranch.getText());
//                ps.setString(6, studSem.getText());
//                ps.setString(7, usernameUpdate.getText());
//                ps.setString(8, String.valueOf(passwordUpdate.getPassword()));
////                ps.setBytes(9, imgPth.getBytes());
////                InputStream img = new FileInputStream(new File(imgPth));
////                ps.setBlob(9, img);
//
//                if(ps.executeUpdate() != 0) {
//                    JOptionPane.showMessageDialog(null, "Updated");
//                }else{
//                    JOptionPane.showMessageDialog(null, "Something Wrong");
//                }
//            
//            
//            } catch (SQLException ex) {
//                Logger.getLogger(updateStud.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            
//        }
//        
//    }
    
    
    private void studPicBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studPicBrowseActionPerformed
        myFunc mf = new myFunc();
        imgPth = mf.browseImage(studPic);
        System.out.println(imgPth);
    }//GEN-LAST:event_studPicBrowseActionPerformed

    private void showPassUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassUpdateActionPerformed
       if(showPassUpdate.isSelected()) {
            passwordUpdate.setEchoChar((char)0);
        } else {
            passwordUpdate.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateStud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField passwordUpdate;
    private javax.swing.JCheckBox showPassUpdate;
    public javax.swing.JTextField studBranch;
    public javax.swing.JTextField studCollId;
    private javax.swing.JButton studInfoUpdate;
    public javax.swing.JTextField studName;
    public javax.swing.JLabel studPic;
    private javax.swing.JButton studPicBrowse;
    public javax.swing.JTextField studRollno;
    public javax.swing.JTextField studSem;
    public javax.swing.JTextField usernameUpdate;
    // End of variables declaration//GEN-END:variables
}
